# configuration file for production environment

# only log warning and error messsages
log: "warning"

# log message to a file in logs/
logger: "file"

# hide errors
show_stacktrace: 0

# disable server tokens in production environments
no_server_tokens: 1

session: Memcached
engines:
  session:
    Memcached:
      memcached_servers: 
        - 127.0.0.1:11211
      fatal_cluster_unreachable: 0
      cookie_name: 'presence_session'
